config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get 'about', to: 'pages#about'
  # Defines the root path route ("/")
  # root "articles#index"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100}
  validates :description, presence: true, length: { minimum: 10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action  :set_article, only: [:show, :edit, :update, :destroy]

  def show

  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit

  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was created sucessfully."
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated sucessfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy

    @article.destroy
    redirect_to articles_path
  end

  private

  def  set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

end

app/controllers/concerns/pages_controller.rb
class PagesController < ApplicationController
  #expects a home.html.erb template+
  def home
  end
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_container.html.erb
<div id="div-container" class="container is-widescreen">
  <div id="div-main-container" class="notification is-primary">
    <%= image_tag("journal.jpg", class:'img-journal') %>
      <div class="bg-text">
    <h2>Welcome to</h2>
    <h1 class="h1-blog">Alpha Blog</h1>
    <p>Completely built on Rails</p>
      </div>
      <div class="div-btn">
        <%= link_to "Articles", articles_path, id:'btn-articles', class:'button is-success' %>
      </div>
  </div>
</div>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
   <h2>The following errors prevented the article from being saved! </h2>
   <ul>
    <% @article.errors.full_messages.each do |message| %>
      <li><%= message %> </li>
    <% end %>
  </ul>
<% end %>


<%= form_with(model: @article, local: true) do |f| %>
    <p>
      <%= f.label :title %>
      <br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :description %>
      <br>
      <%= f.text_area :description %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/articles/_herotag.html.erb
<section id="section-hero" class="hero is-success">
  <div class="hero-body">
    <p class="title">
      Articles
    </p>
    <p class="subtitle">
      Articles Archive
    </p>
  </div>
</section>

app/views/articles/_navbar.html.erb
<nav id="div-navbar" class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
  <h3 class="h3-head">Alpha Blog</h3>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
        <%= link_to "Home", root_path, id:'a-home', class:'navbar-item'%>
        <%= link_to "Articles", articles_path, id:'a-articles', class:'navbar-item'%>

      <div class="navbar-item has-dropdown is-hoverable">
        <a id="a-more" class="navbar-link">
         More
        </a>

        <div class="navbar-dropdown">
          <%= link_to "Create New Article", new_article_path, id:'a-new-article', class:"navbar-item" %>
          <%=link_to 'About', about_path, class:'navbar-item' %>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>
</nav>

app/views/articles/edit.html.erb
<h1>Edit Article!</h1>

<%= render 'form' %>

<%= link_to "Cancel and return to Article listing", articles_path %>

app/views/articles/index.html.erb
<%= render 'articles/navbar' %>
<%= render 'articles/herotag' %>
<div class="box">
  <table id="tb-article" class='table is-hoverable'>
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>

        <!-- List of Articles !-->
        <!-- Pay attention to the % sign where if it doesn't follow a == sign, it means it won't be displayed to the user !-->
        <!-- If %=, then the user can see all the registers stored at @articles !-->

      <% @articles.each do | article | %>
        <tr>
          <td class="td-title"><%= article.title %></td>
          <td class="td-desc"><%= article.description %></td>
          <td><%= link_to 'Read', article_path(article), class:'button is-primary is-small is-outlined' %></td>
          <td><%= link_to 'Edit', edit_article_path(article), class:'button is-info is-small is-outlined' %></td>
          <!-- Link to doesnt work for delete on rails 7. Must use button_to !-->
          <td><%= button_to 'Delete', article_path(article), class:'button is-danger is-small', method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <p><%= link_to 'Create New Article', new_article_path, id:'btn-create', class:'button is-success' %>
</div>

app/views/articles/new.html.erb
<h1>Create new Article!</h1>
<%= render 'form' %>

<%= link_to 'Cancel and return to Articles', articles_path %> </p>

app/views/articles/show.html.erb
<%= render 'navbar' %>

<h1>SHOWING ARTICLES DETAILS</h1>

<p><strong>Title:</strong> <%= @article.title %> </p>
<p><strong>Description: </strong> <%= @article.description %></p>
<br>
<p>
  <%= link_to 'Edit', edit_article_path(@article) %> | <%= button_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?"} %>
</p>

<%= link_to 'Return to Articles', articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NameOfApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
      <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to the about page</h1>

<%=link_to 'Home Page', root_path %>

app/views/pages/home.html.erb
<%= render 'articles/navbar' %>

<%= render 'articles/container' %>

app/views/pages/index.html.erb
<h1>THIS IS HOME PAGE HELLO WORLD!!!</h1>

<%=link_to 'Articles Listing', articles_path %> | <%=link_to 'About Page', about_path %>